name: details-tagging-docker
on: 
  workflow_dispatch:
    inputs:
      tag-version:
        description: 'Version to tag'
        required: false
jobs:
  docker-tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull and push tagged Docker Image
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: ghcr.io/nithach2321/bookinfo-details:uat
          dst: |
            ghcr.io/nithach2321/bookinfo-details:${{needs.git-tag.outputs.tag-version}}